#!/bin/bash
# flagrantior@gmail.com
# Script for train your Morse knowledge


morze=(
	A ".-"
	B "-..."
	C "-.-."
	D "-.."
	E "."
	F "..-."
	G "--."
	H "...."
	I ".."
	J ".---"
	K "-.-"
	L ".-.."
	M "--"
	N "-."
	O "---"
	P ".--."
	Q "--.-"
	R ".-."
	S "..."
	T "-"
	U "..-"
	V "...-"
	W ".--"
	X "-..-"
	Y "-.--"
	Z "--.."

	0 "-----"
	1 ".----"
	2 "..---"
	3 "...--"
	4 "....-"
	5 "....."
	6 "-...."
	7 "--..."
	8 "---.."
	9 "----."
	
	. ".-.-.-"
	, "--..--"
	? "..--.."
)

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m"

printf "
1) Morse to symbol
2) Symbol to Morse

MODE: "
read -n1 mode;
printf "\n"
case $mode in
	1) printf "
.    E   -    T   .----  1
..   I   --   M   ..---  2
...  S   ---  O   ...--  3
.... H   --.  G   ....-  4
...- V   --.- Q   .....  5
..-  U   --.. Z   -....  6
..-. F   -.   N   --...  7
.-   A   -.-  K   ---..  8
.-.  R   -.-- Y   ----.  9
.-.. L   -.-. C   .-.-.- .
.--  W   -..  D   --..-- ,
.--. P   -..- X   ..--.. ?
.--- J   -... b   -----  0
\n"
	stty -echo
	while true; do
		let l=$(( $(shuf -i 1-${#morze[*]} -n 1) -1 )); l=$(( l - l%2 ))
		printf -- "${morze[l+1]} "
		let indent=6
		while read -n1 c; do
			indent=$(( indent-1 ))
			case "$c" in
				.) play -qn synth .05 sin 440;;
				-) play -qn synth .20 sin 440;;
			esac
		done < <(echo -n "${morze[l+1]}")

		read -sn1 a
		a=${a^^}
		if [[ $a == ${morze[l]} ]]; then
			printf "%${indent}s${GREEN}$a${NC}\n"
			play -qn synth .03 sin 880
		else
			printf "%${indent}s${RED}$a${NC} ${morze[l]}\n"
			play -qn synth .1 sin 220
		fi
	done ;;

	2) printf "
A .-    N -.    0 -----
B -...  O ---   1 .----
C -.-.  P .--.  2 ..---
D -..   Q --.-  3 ...--
E .     R .-.   4 ....-
F ..-.  S ...   5 .....
G --.   T -     6 -....
H ....  U ..-   7 --...
I ..    V ...-  8 ---..
J .---  W .--   9 ----.
K -.-   X -..-  . .-.-.-
L .-..  Y -.--  , --..--
M --    Z --..  ? ..--..
\n"
	while true; do
		let l=$(( $(shuf -i 1-${#morze[*]} -n 1) -1 )); l=$(( l - l%2 ))
		printf -- "${morze[l]} "
		read a
		if [[ $a == ${morze[l+1]} ]]; then
			printf "  ${GREEN}${morze[l+1]}${NC}\n"
		else
			printf "  ${RED}${morze[l+1]}${NC}\n"
		fi
	done ;;
esac
stty echo
